### ISSUE TITLE
@Component->components Type Inference Error when separating code and template

### ISSUE THREAD

**Issue by darkflame0** [vuejs/vue-class-component#169] opened 2017-10-17 03:33 UTC
when I put ts code into the *.vue file,the type is corrent
![1](https://user-images.githubusercontent.com/22924199/31645399-747f5942-b32e-11e7-92ec-fda2cdf5ffad.png)

but when code and template were separated into separate files (template in the *.vue,ts code in the *.ts),
the type is inferred VueConstructor<Vue>
![2](https://user-images.githubusercontent.com/22924199/31645413-8271ff46-b32e-11e7-9bcb-c0709d18df2e.png)

**Comment by HerringtonDarkholme** [comment] 2017-10-17 03:55
Sadly, this is by design.
In vue file, type info is specially analyzed by vetur. Ts is analyzed by tsc, which only reads declaration file.

Declaration file only provides most general type info, in this case , VueConstructor

**Comment by darkflame0** [comment] 2017-10-17 04:07
@HerringtonDarkholme 
It means that I cannot separate my code when using components?
I think it's inconvenient...

**Comment by HerringtonDarkholme** [comment] 2017-10-17 04:11
Only imported components have vague type. Unless you aggressively use `$refs`, I don't think there is much inconvenience.

**Comment by ktsn** [comment] 2017-10-17 04:42
As @HerringtonDarkholme explained.
Closing since I don't think this is fixable in vue-class-component.

**Closed by ktsn** 2017-10-17 04:42 UTC
