### ISSUE TITLE
Cannot read property 'props' of undefined` when reading lazily loaded component data

### ISSUE THREAD

**Issue by deraw** [vuejs/vue-class-component#482] opened 2020-11-20 22:45 UTC
Hi!

I'm loading a component written with vue-class-component, and this works perfectly!

However I'm trying to access his data and I get the error `TypeError: Cannot read property 'props' of undefined`
This error appears in the [line 12 of the `collectDataFromConstructor` function](https://github.com/vuejs/vue-class-component/blob/master/src/data.ts#L12)

When I update the condition from `if (vm.$options.props) {` to `if (vm.$options && vm.$options.props) {`, the error is resolved

Reproduction repository: https://github.com/deraw/vue-class-component-issue-482

**Comment by ktsn** [comment] 2020-11-21 03:57
You must bind `this` by `call`. Duplicate of #448

**Closed by ktsn** 2020-11-21 03:57 UTC
