### ISSUE TITLE
Strange errors in vue-class-component v8

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#457] opened 2020-09-20 10:38 UTC
I have a class component like this:

```javascript
import Person from '@/models/Person';
import { PropType } from 'vue';
import { emits, mixins, Options, props } from 'vue-class-component';

const Props = props({
  person: {
    type: Object as PropType<Person>,
    required: true
  }
})

const Emits = emits({
  input: (value) => typeof value === 'number'
})

@Options
export default class HelloWorld extends mixins(Props, Emits) {
  private myData = this.person;

  mounted() {
    this.$emit('input', 2);
  }
}
```

And I receive the following errors:

![Screenshot 2020-09-20 at 12 33 07](https://user-images.githubusercontent.com/17653648/93709279-70aa3080-fb3d-11ea-888c-6c269f75fc79.png)

Here is the repro project which you can run and check this error:
[class-component-test.zip](https://github.com/vuejs/vue-class-component/files/5251464/class-component-test.zip)

I am using:
- vue 3.0.0
- vue-class-component 8.0.0-beta.3

**Comment by ktsn** [comment] 2020-09-20 13:08
Thanks for reporting this. This is caused by the wrong type definition of `@Options`. Will fix it in the next version.

**Comment by ktsn** [comment] 2020-10-04 13:37
fixed in beta.4

**Closed by ktsn** 2020-10-04 13:37 UTC
Labels: bug, v8
