### ISSUE TITLE
Apollo "Cannot set property hello of #< VueComponent> which has only a getter"

### ISSUE THREAD

**Issue by iliyaZelenko** [vuejs/vue-class-component#295] opened 2018-12-08 14:01 UTC
Hello, I use vue-apollo with your library.

I get this error 

> Error in data(): "TypeError: Cannot set property hello of #< VueComponent> which has only a getter"

when I have this code

```ts
@Component({
  apollo: {
    hello: {
      query: gql`{hello}`
    }
  }
})
export default class Home extends Vue {
  hello = 'test'
}
```

Am I doing something wrong or is it a bug?

### Versions:

vue-class-component **6.3.2**
vue **2.5.18** (recently released, maybe that's the problem)

I do not even know how to replace vue 2.5.18 with 2.5.17.  
I don't have vue in "dependencies" (using nuxt)
I have yarn, i tried 
```json
"resolutions": {
    "vue": "2.5.17"
}
```

and than `yarn install`, but `yarn info vue version` shows 2.5.18

---

Also the following code will work:

```ts
@Component({
  data () {
    return {
      hello: 'test'
    }
  },
  apollo: {
    hello: {
      query: gql`{hello}`
    }
  }
})
export default class Home extends Vue {}
```

**Comment by ktsn** [comment] 2018-12-09 04:47
Please provide a minimal / self-contained reproduction when you report a bug. Thanks.

**Comment by chs97** [comment] 2018-12-10 02:37
Type 'VueClass<Vue>' is not assignable to type 'typeof App'.
    Types of parameters 'options' and 'options' are incompatible.
      Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> | undefined' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, any, any, any, any> | undefined'.
        Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, any, any, any, any>'.
          Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>' is not assignable to type 'ComponentOptions<Vue, any, any, any, any[], Record<any, any>>'.



vue@2.5.19   @ktsn

**Comment by ktsn** [comment] 2018-12-10 02:56
It is not a reproduction and not seems to be related to this issue. See #294

**Comment by iliyaZelenko** [comment] 2018-12-10 13:02
Well, I will try to show on the project when will i have time. But I have exactly this error. 

Perhaps she is also associated with [apollo-module](https://github.com/nuxt-community/apollo-module) package for nuxt. 

The error is rather strange, if property is in the class, then how it can only have a getter?

**Comment by ktsn** [comment] 2019-01-16 13:05
Sorry we cannot help you without reproduction. Closing until reproduction is provided.

**Closed by ktsn** 2019-01-16 13:05 UTC
Labels: need repro
