### ISSUE TITLE
Cannot access to this.$router in custom method

### ISSUE THREAD

**Issue by MrDarkSkil** [vuejs/vue-class-component#252] opened 2018-06-04 09:31 UTC
Hi, i would like to access to `this.$router.push('/home')` in a custom method, i get this error `Cannot read property 'push' of undefined`

```typescript
import Vue from 'vue'
import Component from 'vue-class-component'
import AuthService from "../../../../main/services/api/auth/auth.service";

@Component
export default class Login extends Vue {

    login: string = "";
    password: string = "";

    /**
     * Classes
     */
    authService = this.$container.get<AuthService>(AuthService.name);

    submit() {
        console.log('login: ' + this.login);
        console.log('password: ' + this.password);
        this.authService.login(this.login, this.password).then((res) => {
            console.log(this);
            this.$router.push('/home');
        });
        return false;
    }

    mounted() {
        console.log(this);
    }
}


```

```vue
<template>
    <div>
        <form v-on:submit.prevent="submit()">
            <input name="login" v-model="login"/><br>
            <input name="password" type="password" v-model="password"/>
            <button type="submit"></button>
        </form>

    </div>
</template>

<script lang="ts">
   import Login from './Login'
   export default Login
</script>

<style scoped>

</style>

```

**Comment by MrDarkSkil** [comment] 2018-06-04 09:48
When i try 

```typescript
import Vue from 'vue'
import Component from 'vue-class-component'
import {remote} from 'electron'
import AuthService from "../../../../main/services/api/auth/auth.service";

@Component
export default class Login extends Vue {

    login: string = "";
    password: string = "";

    /**
     * Classes
     */
    authService = this.$container.get<AuthService>(AuthService.name);

    submit = () => {
        this.$router.push('/home');
    }

    mounted() {

    }
}

```

i get

`
Uncaught TypeError: Cannot read property '_router' of undefined
`

**Comment by ktsn** [comment] 2018-06-04 09:50
Hi, please provide a reproduction when reporting a bug.

**Comment by MrDarkSkil** [comment] 2018-06-04 12:22
the code above is not enough?

**Comment by ktsn** [comment] 2018-06-04 12:45
Reproduction should be self-contained, minimal and executable out of the box so that we can confirm whether it is a real problem or not. You can use jsfiddle.net or example GitHub repo to make it.

**Comment by kaorun343** [comment] 2018-06-05 00:26
Did you import vue-router?

**Comment by MrDarkSkil** [comment] 2018-06-06 08:28
Yes of curse x) @kaorun343 

Work fine with 
```typescript
import Vue from 'vue'
import {remote} from 'electron'
import AuthService from "../../../../main/services/api/auth/auth.service";
import {IModuleRepository, default as ModuleService} from "../../../../main/services/module/module.service";

export default Vue.extend({
    data() {
        return {
            login: "",
            password: ""
        }
    },
    methods: {
        submit: function() {
            console.log('login: ' + this.login);
            console.log('password: ' + this.password);
            const authService = this.$container.get<AuthService>(AuthService.name);
            const moduleService = this.$container.get<ModuleService>(ModuleService.name);
            authService.login(this.login, this.password).then((res) => {
                this.$router.push('/home');
            });
        }

    },

    mounted() {

    }
});


```

**Comment by ktsn** [comment] 2018-07-03 14:16
Closing as reproduction is not provided in a long time. Please open a new issue with a self-contained reproduction when you can follow up information.

**Closed by ktsn** 2018-07-03 14:16 UTC
Labels: need repro

**Comment by Worie** [comment] 2019-08-30 08:58
Sorry for reviving old issue, but I experience exactly the same thing - following exactly the same tech stack (Electron, TypeScript, VueClassComponent, Vue, VueRouter) - I don't have the reproduction either, unfortunately -  though I suspect it might be down to some `electron-webpack-vue` packages or similar that do some configuration automagically, because I've been using exactly the same stack, but without electron and it seemed working. Passing regular object (non decorated) works.

I just wanted to ask @MrDarkSkil whether you found solution to your problem?

**Comment by MrDarkSkil** [comment] 2019-09-03 08:55
Hi @Worie, i never found a solution unfortunately...

**Comment by Worie** [comment] 2019-09-03 09:34
That's a pity, thanks for your time @MrDarkSkil - I guess I'll stop using the decorator for this particular project, at least for now.

**Comment by avmalexisl** [comment] 2019-10-10 10:42
Hi,
I have the same problem, I cannot access `this.$router` within the response callback of a service:

**Simple reproduction case**

`import Vue from "vue";`
`import Component from "vue-class-component";`
`@Component`
`export default class SomeComponent extends Vue {`
`  public SomeService() {`
    `return this.$http.get("api/endpoint/path")`
      `.then((response) => {`
        `// do something`
        `this.$router.push({ name: "home" });`
      `}, (error) => {`
        `// error callback`
      `});`
  `}`
`}`

I tried removing the @Component decorator and it didn't work out as mentioned before, and didn't help that I didn't use the arrow functions as mentioned here [https://github.com/vuejs/vue-class-component/issues/302](url)
