### ISSUE TITLE
Registering Hooks on Component class

### ISSUE THREAD

**Issue by Fred-JulieDesk** [vuejs/vue-class-component#264] opened 2018-08-27 16:49 UTC
Hello,

I recently faced an issue with the method 

```
Component.registerHooks([
        'beforeRouteEnter',
    ]);

```
It was not properly registering my hook.
I digged in the code of your library and found that the method was called after the App component (I'm using vue-cli-3) and thus the hook was not properly registered on the components, causing them to not trigger it.

I was initially doing as you suggest in your README and calling 

```
import { Component } from 'vue-property-decorator';

Component.registerHooks([
    'beforeRouteEnter',
]);

```

in my main.ts before anything else.

However this did not work because of the reason above.

I found a solution by importing it in the App.vue component before the decorator

`@Component`

Now the hook is working properly, so if anyone is facing this problem with vue-cli-3 using typescript, here is the solution:

```
<script lang="ts">
    import { Component, Prop, Vue } from 'vue-property-decorator';
   Component.registerHooks([
        'beforeRouteEnter',
    ]);

    @Component
    export default class App extends Vue {
```
Happing coding

**Comment by ktsn** [comment] 2018-08-27 22:50
Please provide a self-contained repro if you are reporting a bug. Thanks.

**Comment by ktsn** [comment] 2018-08-27 22:55
Note I suspect this is the same with a #193

**Comment by dragosbodin** [comment] 2018-09-17 11:13
Any updates over here? Still getting this issue with vue-cli 3.

**Comment by ktsn** [comment] 2018-09-29 11:34
Closing until reproduction is provided.

**Closed by ktsn** 2018-09-29 11:34 UTC
Labels: need repro

**Comment by kevlarr** [comment] 2019-02-14 01:09
@maritaria Ah great catch! I wasn't following the docs because I thought I could just put that code into `main.ts` and that explicit import worked for me as well.

**Comment by bodograumann** [comment] 2021-03-22 14:25
Same here @kevlarr. The worst thing about this for me was, that after HMR ran it actually did work, because then the main.ts was already evaluated. So whenever I tried to debug the problem, it did not occur anymore... :rage:

**Comment by kevlarr** [comment] 2021-03-22 16:04
@bodograumann Ugh, that's especially frustrating!
