### ISSUE TITLE
Add an option to load style file from

### ISSUE THREAD

**Issue by antoine-pous** [vuejs/vue-class-component#230] opened 2018-03-08 17:10 UTC
Hi!

I'm currently facing a problem, i won't use an all in one file to write my components. When i try to split the component in 3 parts (template, class, style) i can't import the style file and don't find any documentation about a workaround or a way to do it.

It would be really cool to see a ComponentOptions `style` to do it, so we can import our style files without polluting the template and the code.

Here is my apporach, tell me if i'm doing something wrong.

### Template
```html
<nav id="menu-top">
    <li>
        <ul id="account-menu">
            <li class="login">
                <a href="#login">
                    <font-awesome-icon icon="user" /> Login
                </a>
            </li>
        </ul>
    </li>
</nav>
```
### Style
```less
nav#menu-top {
  background-color: blue;
}
```
### Code (typescript)
```typescript
import { Vue, Component, Prop } from "vue-property-decorator";

@Component({
    template: require("./MenuTop.html"),
    style: [{"less-loader": ["./MenuTop.less"]}] // This option would be really usefull
})
export default class MenuTop extends Vue {
  // Menu stuff
}
```
I've tried to use a `style` element into the template but this is not acceptable and webpack throw this error: 

```console
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
```

Thank you!

**Comment by ktsn** [comment] 2018-03-08 17:23
Duplicate of #15 and #149

**Closed by ktsn** 2018-03-08 17:23 UTC

**Comment by gsafety1** [comment] 2019-03-21 00:57
@antoine-pous 
I have the same idea as you.  Find a good solution later.
use [vue-css-ts](https://github.com/numsg/vue-css-ts)
[smaples](https://github.com/numsg/vue-seed)
