### ISSUE TITLE
Data initialization with props does not work properly after updating Vue.js to 2.2.0

### ISSUE THREAD

**Issue by kimamula** [vuejs/vue-class-component#68] opened 2017-02-26 06:20 UTC
### Steps to reproduce
1. Update vue, vue-template-compiler to 2.2.0
2. `npm run example`
3. Open example.html in a browser

### Expected behavior
`helloMsg` is initialized to `Hello, World`

### Actual behavior
`helloMsg` is initialized to `Hello, undefined`

**Comment by ktsn** [comment] 2017-02-26 07:09
Thank you for reporting this issue.
This is likely caused by Vue 2.2's internal changes (for `$props`). I'll modify vue-class-component to fix this issue.

**Comment by yyx990803** [comment] 2017-02-27 17:09
This is now fixed in 5.0.0 (note you will also need to enable `allowSyntheticDefaultImports` in TS compile options).

**Closed by yyx990803** 2017-02-27 17:09 UTC
Labels: bug
