### ISSUE TITLE
class methods not working in jest

### ISSUE THREAD

**Issue by gforceg** [vuejs/vue-class-component#372] opened 2019-11-19 00:18 UTC
I am having problems calling a component method within a jest test.
I [created a project](https://github.com/gforceg/vue-ts-jest-method-test) using the CLI and specified both typescript and jest when creating the project and I cannot call public methods within the unit tests without doing something like this:

```typescript
(wrapper.vm as any).myMethod()
```

The error is:

```bash
    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    tests/unit/HelloWorld.spec.ts:13:18 - error TS2339: Property 'sayHello' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>>'.

    13       wrapper.vm.sayHello()
                        ~~~~~~~~
```

Is this an issue w/ the `shallowMount` function?

I do not have access to chat.vuejs.org due to my organization's firewall / use policy.

Thanks!

**Comment by ktsn** [comment] 2019-11-19 02:15
Duplicate of #340

**Closed by ktsn** 2019-11-19 02:15 UTC
