### ISSUE TITLE
Strange behavior when using jest

### ISSUE THREAD

**Issue by blocka** [vuejs/vue-class-component#122] opened 2017-07-07 04:31 UTC
Not sure where this issue belongs as it doesn't seem to be specific to vue-class-component, and there are probably a lot of moving pieces here, but I'll try anyway.

If I put _anything_ inside a class where I'm extending vue (in a .vue file), vue-loader (I guess?) seems to ignore the exported component...as if there was no script tag, at all.

I'm pretty certain this behavior only happens when running my test through jest. Maybe something is missing in the pipeline?

Here is a repo with test using jest illustrating the problem: https://github.com/blocka/strange-jest-behavior

**Comment by ktsn** [comment] 2017-07-08 08:59
I've briefly look into it but I'm not sure what is the root cause of this problem...
Maybe, some problem happens in transforming process by [jest-vue-preprocessor](https://github.com/vire/jest-vue-preprocessor) since it seems to transform `.vue` files for Jest?

**Comment by ktsn** [comment] 2017-11-01 14:09
Looks like this problem is fixed with the latest jest-vue-preprocessor (v1.3.1) 🎉

**Closed by ktsn** 2017-11-01 14:09 UTC
