### ISSUE TITLE
Type definition file disables intellisense in VS Code with Vetur

### ISSUE THREAD

**Issue by KokoDoko** [vuejs/vue-class-component#191] opened 2017-11-10 13:05 UTC
I have downloaded the example files from this repository. I have not changed anything. I get the following issue when using Vetur and VS Code:

When including the **sfc.d.ts** file, intellisense for .vue files gets disabled. I don't get errors for importing non-existing files, and code changes in .vue files are not reflected in intellisense.

```
    declare module "*.vue" {
      import Vue from 'vue'
      export default Vue
    }
```

**index.ts**

```
    // import only works when INCLUDING the sfc.d.ts file
    import App from './components/app.vue'
```

**app.vue**

```
    <template></template>
    <script lang="ts">
        // intellisense is completely disabled unless I EXCLUDE the sfc.d.ts file!
        import Card from "./notexisting/nothing.vue"      // no error
    </script>
    <style></style>
```

**Comment by HerringtonDarkholme** [comment] 2017-11-10 13:19
Please read https://github.com/vuejs/vetur/issues/423#issuecomment-340333844

**Comment by KokoDoko** [comment] 2017-11-10 13:31
Thanks, but is using an alpha plugin instead of Vetur really a good idea? I expected that using Vue with Typescript would be officially supported by now :) Which makes me suspect that the issue has to be on my end...

**Comment by ktsn** [comment] 2017-11-11 03:22
```ts
declare module "*.vue" {
```

This means all assets that matches this pattern will have the declared types. So this is expected behavior.
https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations

If you want to change this behavior, you need to use extra ts plugin.

Closing since there are nothing we can do for this behavior in vue-class-component side.

**Closed by ktsn** 2017-11-11 03:22 UTC

**Comment by KokoDoko** [comment] 2017-11-11 08:50
Thanks. This essentially means that vue can't be used with typescript out of the box. Surprising!

**Comment by HerringtonDarkholme** [comment] 2017-11-11 10:04
@kokodoko Please Use webstorm
