### ISSUE TITLE
example error with typescript 2.6.1

### ISSUE THREAD

**Issue by keenwon** [vuejs/vue-class-component#181] opened 2017-11-01 08:45 UTC
```shell
$ npm install && npm run example
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> vue-class-component@6.0.0 example D:\Test\vue-class-component
> npm run build && webpack --config example/webpack.config.js


> vue-class-component@6.0.0 build D:\Test\vue-class-component
> npm run build:ts && npm run build:main


> vue-class-component@6.0.0 build:ts D:\Test\vue-class-component
> tsc -p .

src/component.ts(38,16): error TS2532: Object is possibly 'undefined'.
src/component.ts(40,58): error TS2532: Object is possibly 'undefined'.
src/component.ts(41,16): error TS2532: Object is possibly 'undefined'.
src/component.ts(41,34): error TS2532: Object is possibly 'undefined'.
src/component.ts(44,14): error TS2532: Object is possibly 'undefined'.
src/component.ts(45,14): error TS2532: Object is possibly 'undefined'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:ts"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-class-component@6.0.0 build:ts: `tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vue-class-component@6.0.0 build:ts script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-class-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-class-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-class-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Test\vue-class-component\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-class-component@6.0.0 build: `npm run build:ts && npm run build:main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-class-component@6.0.0 build script 'npm run build:ts && npm run build:main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-class-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:ts && npm run build:main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-class-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-class-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Test\vue-class-component\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "example"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-class-component@6.0.0 example: `npm run build && webpack --config example/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-class-component@6.0.0 example script 'npm run build && webpack --config example/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-class-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && webpack --config example/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-class-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-class-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Test\vue-class-component\npm-debug.log

```

package info:

```shell
$ npm ls --depth 0
vue-class-component@6.0.0 D:\Test\vue-class-component
+-- @types/chai@4.0.4
+-- @types/mocha@2.2.44
+-- babel-core@6.26.0
+-- babel-loader@7.1.2
+-- babel-plugin-transform-class-properties@6.24.1
+-- babel-plugin-transform-decorators-legacy@1.3.4
+-- babel-preset-es2015@6.24.1
+-- chai@4.1.2
+-- css-loader@0.28.7
+-- mocha@4.0.1
+-- rimraf@2.6.2
+-- rollup@0.50.0
+-- rollup-plugin-replace@2.0.0
+-- testdouble@3.2.6
+-- ts-loader@2.3.7
+-- typescript@2.6.1
+-- uglify-js@3.1.6
+-- vue@2.5.2
+-- vue-loader@13.3.0
+-- vue-template-compiler@2.5.2
`-- webpack@3.8.1
```

**Comment by justerest** [comment] 2017-11-01 09:07
I have problem after updating typescript too.

`TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type '<VC extends VueClass<Vue>>(target: VC) => VC' is not assignable to type 'typeof Game1Main'.
    Property 'extend' is missing in type '<VC extends VueClass<Vue>>(target: VC) => VC'.
`

**Comment by keenwon** [comment] 2017-11-01 09:11
@justerest same with you.

![image](https://user-images.githubusercontent.com/5516478/32267817-7b4d15d4-bf27-11e7-949d-eef9a8332a67.png)

https://github.com/keenwon/vue-normailzr-example

**Comment by justerest** [comment] 2017-11-01 10:34
@keenwon, there is new feature in typescript 2.6 
[https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments](url)
I just mute it and it work.

**Comment by keenwon** [comment] 2017-11-01 11:04
@justerest 
uh...... it works, but not a good idea.

**Comment by ktsn** [comment] 2017-11-01 14:00
This seems only to happen if we compile it with ts-loader. tsc does not provide such errors. I have no idea what is the root cause.

@HerringtonDarkholme Do you have any idea to fix this?

**Comment by schoening** [comment] 2017-11-01 14:19
Could this be related to TypeScripts new feature?

> **Invoke uncalled decorators**
Occasionally you might try to use a decorator without calling it first.
Thankfully, TypeScript can use some basic heuristics to figure these scenarios out, and can provide a useful error message with a handy quick-fix to correct from something like @Input to @Input().

https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/

**Comment by HerringtonDarkholme** [comment] 2017-11-01 14:55
@ktsn We need to update Vuex type definition. TS2.6 disallows `export default` expression in d.ts. 

The breaking of Vuex causes other erros. in @keenwon 's example.

**Comment by ktsn** [comment] 2017-11-01 15:09
@HerringtonDarkholme I guess there is another cause regarding this problem because the example in this repo also get this kind of error even though it does not depends on Vuex.

**Comment by HerringtonDarkholme** [comment] 2017-11-01 15:17
@ktsn Oh, I see. 

I guess the problem is strictFunctionTypes. Investigating.

**Comment by HerringtonDarkholme** [comment] 2017-11-01 15:27
Already fixed in https://github.com/vuejs/vue/pull/6819. need releasing.

**Comment by ktsn** [comment] 2017-11-01 15:42
Thanks for investigation. OK, let's wait the next vue release.

**Closed** 2017-11-01 15:43 UTC

**Comment by darylteo** [comment] 2017-11-06 07:54
Hi all, just encountered this issue (or something similar) and it was blocking me majorly.

You can downgrade to 2.5, or add "strictFunctionTypes": false temporarily to get across this hurdle. 

Not sure why this was closed, because this was a hard one to figure out. Hope this helps any others (and thanks @HerringtonDarkholme for the key piece of information I needed 👍 )

**Comment by HerringtonDarkholme** [comment] 2017-11-06 07:57
@darylteo Vue2.5.3 has released. Try it!

**Comment by darylteo** [comment] 2017-11-06 07:59
@HerringtonDarkholme woot! just tried it and it works! thanks x2!

**Comment by sbmw** [comment] 2017-11-20 18:34
Sorry, I still seem to have some problems here when using inheritance.

This works fine:

@Component({})
export class MyComponent extends Vue {
}

But if I go for something like:

export abstract class MyBaseComponent extends Vue {
}

@Component({})
export class MyComponent extends MyBaseComponent {
}

I get errors along the lines of TS2345: Argument of type 'typeof MyClass ' is not assignable to parameter of type 'VueClass<Vue>'

Sorry if I'm missing something obvious but I've been banging my head against this for a while now. Thanks!

**Comment by vladyslav2** [comment] 2018-03-10 07:55
if you updated Vue and still have same issue - make sure you did not forget to update vue-loader, vue-template-compiler and etc

**Comment by PSausM** [comment] 2018-03-20 09:17
Where can I find information which version of vue, typescript, vue-loader work together. It's really a nightmare.

**Comment by vladyslav2** [comment] 2018-03-20 15:49
I'm not sure if I can do this, if not please delete my post

@PSausM I was very confused too so I decide to create an article how to fix every issue I got https://webdevelop.pro/vuejs-with-typescript.html

**Comment by JianShaw** [comment] 2018-12-08 06:53
It happens today.my typescript version is 3.2.3. add `"strictFunctionTypes": false` solve my problem.

**Comment by rhinyx** [comment] 2018-12-08 17:16
Having same issue today with a fresh installation.

**Comment by skyfly200** [comment] 2018-12-09 01:53
Same issue today as well with a fresh install. Been using Vue-CLI for a few weeks and I love it! So far trying typescript has been the largest hurdle I've reached with it, and seeing as I just started learning typescript it's even more painful. How can we get the fresh install to build smoothly without needing modification, so beginners to Vue can feel even more comfortable. It would be so great if this could be resolved!

**Comment by adrianjord** [comment] 2018-12-09 03:41
Was going through the [Microsoft Vue TypeScript Vue Starter](https://github.com/Microsoft/TypeScript-Vue-Starter) tutorial thing and ran into this issue. I agree with @skyfly200, would be nice to resolve for anyone new coming in that may not think to search the error.

**Comment by ktsn** [comment] 2018-12-09 05:04
Please don't post to the issue which is closed 1 year ago. The issue with Vue v2.5.18 is already filed on #294
