### ISSUE TITLE
Using vue-class-comopnent results in "Super expression must either be null or a function" when Vue is external

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-class-component#355] opened 2019-08-16 10:00 UTC
I found a problem when using `vue-class-component` for a library project in conjunction with using `vue-cli`. `vue-cli-service --target lib` externalized `Vue` for the library, resulting in `Vue` being `undefined` when consumed by another package. See the minimal repro (it uses yarn workspaces).

# main package - (main.ts)

```ts
import Vue from 'vue';
import Component from 'vue-class-component';

console.log(Vue); // is undefined when consumed by another package

@Component
export default class BaseComponent extends Vue {
  public created() {
    console.log('base component');
  }
}

export {
  BaseComponent,
};
```

# sub package - (main.ts)

```ts
import * as test from 'main';

console.log(test); // app already crashed because `extends Vue` didn't work
```

https://github.com/johannes-z/vue-class-component-external-vue

**Comment by nelisbijl** [comment] 2019-10-29 09:46
I am experiencing the same problem. Did you resolve this?

**Comment by LinusBorg** [comment] 2019-10-29 10:40
This is not inherent to `class-component`. Most Vue libs using this package right here or not, will import Vue, e.g. to install themselves as a plugin (`Vue.use()`).

So any project importing such a lib has to have vue in its package.json's dependencies, then webpack can resolve 'vue' and the import doesn't fail.

If this doesn't work in your workspaces setup, you will have to provide a reproduction.

**Comment by simllll** [comment] 2020-01-08 11:56
Did you solve the issue? I'm experiecing something similar right now, but due tot he fact that I've removed the useBuiltIn: usage flag in my webpack's library config.

**Comment by ktsn** [comment] 2020-04-26 16:09
Closing as this is likely due to a bundler and its configuration. If you find something in Vue Class Component causes this issue, please open a new issue with a reproduction. Thank you!

**Closed by ktsn** 2020-04-26 16:09 UTC
